AWSTemplateFormatVersion: '2010-09-09'
Description: >
    AWS Cloud Formation Lambda Template: Resources:
    - AWS EC2 Instance with Amazon Linux AMI, 
    - AWS Security Group, 

    GitHub Repository:
    https://github.com/huuboo96/DBS_Epic2/tree/DBS_Epic2_Task1

Parameters:

  AvailabilityZone:
    Description: An Availability Zone.
    Type: String
    Default: eu-central-1a
    ConstraintDescription: Must be a valid Availability Zone

  InstanceType:
    Description: Amazon EC2 instance type.
    Type: String
    Default: t2.micro
    ConstraintDescription: Must be a valid Amazon EC2 instance type.

  ImageId:
    Type: String
    Description: 'Linux 2 AMI for eu-central-1 Region'
    Default: ami-0474863011a7d1541

  KeyPairName:
    Description: Name of an existing Amazon EC2 key pair to enable SSH or RDP access
      to the instances.
    Type: String
    Default: Azkaban
    MinLength: '1'
    MaxLength: '255'
    AllowedPattern: "[\\x20-\\x7E]*"
    ConstraintDescription: KeyPairName is a required Field and can contain only ASCII
      characters.

  SSHLocation:
    Description: The IP address range that can be used to connect using SSH or RDP
      to the Amazon EC2 instances.
    Type: String
    MinLength: '9'
    MaxLength: '18'
    Default: 0.0.0.0/0
    AllowedPattern: "(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})/(\\d{1,2})"
    ConstraintDescription: Must be a valid IP CIDR range of the form x.x.x.x/x.


Resources:

  InstanceKeyPair:
    Type: 'AWS::EC2::KeyPair'
    Properties:
      KeyName: !Ref KeyPairName

  Instance:
    Type: 'AWS::EC2::Instance'
    Properties: 
      ImageId: !Ref ImageId
      InstanceType: !Ref InstanceType
      AvailabilityZone: !Ref AvailabilityZone
      KeyName: !Ref KeyPairName
      #SecurityGroupIds: 
      #  - !Ref SecurityGroup
      #IamInstanceProfile: !Ref InstanceProfile
      NetworkInterfaces: 
      - AssociatePublicIpAddress: "true"
        DeviceIndex: "0"
        #GroupSet: 
        #  - !GetAtt SecurityGroup.GroupId
        #SubnetId: 
        #  Ref: "Subnet"

  EC2SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: SSH access
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: '22'
        ToPort: '22'
        CidrIp: !Ref 'SSHLocation'

Outputs:

  KeyPairId:
    Description: Instance KeyPair Id
    Value: !GetAtt InstanceKeyPair.KeyPairId
  
  InstanceDnsName:
    Description: Instance Public DNS name
    Value: !GetAtt Instance.PublicDnsName

  InstanceId:
    Description: Instance Id 
    Value: !Ref Instance